-- spaces = require("hs._asm.undocumented.spaces")
--
-- local space_manager = { "cmd", "alt", "ctrl" }
--
-- local one_screens = {
--   {
--     shortcut = "1",
--     configs = {
--       { app = "Postman", screen = "center", position = "full" },
--       { app = "Spark", screen = "center", position = "full" },
--       { app = "Safari", screen = "center", position = "full" },
--       { app = "Firefox", screen = "center", position = "full" }
--     }
--   }
-- }
--
-- local configs = one_screens
--
-- local left   = hs.screen('-1,0')
-- local center = hs.screen('0,0')
-- local right  = hs.screen('1,0')
--
-- hs.hotkey.bind(space_manager, '.', hs.hints.windowHints)
--
-- hs.hotkey.bind(space_manager, "Z", function()
--   for k, v in ipairs(configs) do
--     
--     for k, v in ipairs(v.configs) do
--       hs.application.open(v.app)
--     end
--
--     hs.hotkey.bind(space_manager, v.shortcut, function()
--       hs.alert.show("All spaces created")
--     end)
--   end
-- end)
--
-- hs.hotkey.bind(space_manager, "X", function()
--   for k, v in ipairs(configs) do
--     for k, v in ipairs(v.configs) do
--       app = hs.application.get(v.app)
--       window = app:mainWindow()
--       window:setFullScreen(true)
--     end
--   end
--   hs.alert.show("All spaces removed")
-- end)
--
-- hs.hotkey.bind(space_manager, "C", function()
--   for k, v in ipairs(configs) do
--     for k, v in ipairs(v.configs) do
--       app = hs.application.get(v.app)
--       app:kill()
--     end
--   end
--   hs.alert.show("All spaces removed")
-- end)
