#+/bin/bash

./install-ack.sh
./install-bat.sh
./install-curl.sh
./install-fzf.sh
./install-ghostty.sh
./install-git.sh
./install-go.sh
./install-jq.sh
./install-jqp.sh
./install-libpq.sh
./install-nvm.sh
./install-stow.sh
./install-tfenv.sh
./install-tmux.sh
./install-tmuxinator.sh
./install-tree.sh
./install-zsh.sh
