#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 <environment>"
    exit 1
fi

AWS_PROFILE=$1
AWS_REGION=us-east-1

TMUX_WINDOW_NAME="AWS ${AWS_PROFILE}"

echo $TMUX_WINDOW_NAME

tmux new-window -n "$TMUX_WINDOW_NAME"
tmux send-keys -t "$TMUX_WINDOW_NAME" "export AWS_PROFILE=$AWS_PROFILE;export AWS_REGION=$AWS_REGION" C-m
tmux send-keys -t "$TMUX_WINDOW_NAME" "aws sso login" C-m
tmux send-keys -t "$TMUX_WINDOW_NAME" "clear" C-m
