#!/bin/bash

CACHE_DIR=~/.init/cache/${AWS_PROFILE}
CACHE_FILE_NAME=aws_ssm.cache
CACHE_SSM=$CACHE_DIR/$CACHE_FILE_NAME

NAME="$(cat $CACHE_SSM | fzf)"

echo $NAME
aws ssm get-parameters --name "$NAME"  --with-decryption | jq ".Parameters[] | .Value"
