#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 <service-name>"
    exit 1
fi

SERVICE_NAME=$1

watch -n 1 "aws ecs describe-tasks --tasks $(aws ecs list-tasks --service-name $SERVICE_NAME --query 'taskArns' --output text) | jq '.tasks[] | {taskDefinitionArn, lastStatus, createdAt}'"

